### Today
@exercise_name = plank
GET {{host}}/today

### Get statistics for a given exercise
GET {{host}}/exercises/{{exercise_name}}/stats


### Send POST request with json body
POST {{host}}/duration
Content-Type: application/json

{
  "name": "plank",
  "duration": 60
}


### Send POST request with json body
POST {{host}}/reps
Content-Type: application/json

{
  "name": "biceps curls",
  "reps": 10
}

### Send POST to get auth token
POST {{host}}/api/set_auth_token/
Content-Type: application/x-www-form-urlencoded

password=my_strong_password

