services:
  db-dev:
    image: postgres:18-alpine
    env_file:
      - compose.dev.env
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  app-dev:
    image: ghcr.io/miszo97/exercices-backend:dev
    build: .
    env_file:
      - compose.dev.env
    ports:
      - "8090:8080"
    volumes:
      - .:/app

volumes:
  pgdata_dev:
